version: "3"

services:
  cache:
    image: 'redis:alpine'
    restart: always
    # hostname: chatapp-redis
    container_name: chatapp-redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - cache:/data
  db:
    image: postgres:alpine
    restart: always
    container_name: chatapp-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
  cache:
    driver: local
